dist: trusty
sudo: false
language: python
python:
- "3.5"
install:
- pip install -r requirements.txt
- npm install --global raml2html
script:
- raml2html --version
- coverage run -m unittest -v
notifications:
  email: false
after_success:
  - coveralls
