dist: trusty
sudo: false
language: python
python:
- "3.5"
install:
- pip install -r requirements.txt
- wget http://central.maven.org/maven2/org/openapitools/openapi-generator-cli/3.1.1/openapi-generator-cli-3.1.1.jar -O /preparer/openapi-generator-cli-3.1.1.jar
script:
- raml2html --version
- coverage run -m unittest -v
notifications:
  email: false
after_success:
  - coveralls
