#%RAML 1.0
# From https://github.com/mulesoft/api-console/blob/master/dist/examples/instagram.raml
---
title: Instagram API Sample RAML File
version: v1
description: |
  A sample RAML spec using Instagram's API
baseUri: https://api.instagram.com/{version}
securitySchemes:
  - oauth_2_0:
      description: |
        test
      type: OAuth 2.0
      describedBy:
        queryParameters:
          access_token:
            description: test
            type: string
      settings:
        authorizationUri: https://api.instagram.com/oauth/authorize
        accessTokenUri: https://api.instagram.com/oauth/access_token
        authorizationGrants: [ code, token ]
        scopes:
          - basic
          - comments
          - relationships
          - likes
securedBy: [ oauth_2_0 ]
mediaType: application/json
traits:
  - limitableById:
      queryParameters:
        min_id:
          description: Return media later than this min_id.
          type: integer
        max_id:
          description: Return media earlier than this max_id.
          type: integer
  - limitableByTime:
      queryParameters:
        max_timestamp:
          description: Return media before this UNIX timestamp.
          type: integer
        min_timestamp:
          description: Return media after this UNIX timestamp.
          type: integer
resourceTypes:
  - base:
      get?:
        queryParameters:
          callback:
            description: test
            type: string
            example: callbackFunction
            required: false
          count:
            description: Number of items you would like to receive.
            type: integer
            example: 1
            required: false
        responses:
          503:
            description: test
      post?:
        responses:
          503:
            description: test
      delete?:
        responses:
          503:
            description: test
documentation:
  - title: test chapter
    content: Nothing here.
  - title: Authentication
    content: |
      testing documentation
# Oembed
/p/{shortcode}/media:
  uriParameters:
    shortcode:
      type: string
      required: true
  type: base
  get:
    description: |
      Given a short link, issues a redirect to that media's JPG file.
    queryParameters:
      size:
        enum:
          - t,
          - m,
          - l
        default: m
    responses:
      302:
        body:
          text/html:
            example: |
              HTTP/1.1 302 FOUND
              Location: http://distillery.s3.amazonaws.com/media/2010/10/02/7e4051fdcf1d45ab9bc1fba2582c0c6b_6.jpg
