#%RAML 1.0
# From https://github.com/mulesoft/api-console/blob/master/dist/examples/instagram.raml
---
title: Instagram API Sample RAML File
version: v1
description: |
  A sample RAML spec using Instagram's API
baseUri: https://api.instagram.com/{version}
securitySchemes:
  - oauth_2_0:
      description: |
        Instagram’s API uses the OAuth 2.0 protocol for simple, but effective
        authentication and authorization. The one thing to keep in mind is that
        all requests to the API must be made over SSL (https:// not http://)
      type: OAuth 2.0
      describedBy:
        queryParameters:
          access_token:
            description: |
              Used to send a valid OAuth 2 access token. Do not use together
              with the "Authorization" header
            type: string
      settings:
        authorizationUri: https://api.instagram.com/oauth/authorize
        accessTokenUri: https://api.instagram.com/oauth/access_token
        authorizationGrants: [ code, token ]
        scopes:
          - basic
          - comments
          - relationships
          - likes
securedBy: [ oauth_2_0 ]
mediaType: application/json
traits:
  - limitableById:
      queryParameters:
        min_id:
          description: Return media later than this min_id.
          type: integer
        max_id:
          description: Return media earlier than this max_id.
          type: integer
  - limitableByTime:
      queryParameters:
        max_timestamp:
          description: Return media before this UNIX timestamp.
          type: integer
        min_timestamp:
          description: Return media after this UNIX timestamp.
          type: integer
resourceTypes:
  - base:
      get?:
        queryParameters:
          callback:
            description: |
              Callback function name. All output will be wrapper under this
              function name.
            type: string
            example: callbackFunction
            required: false
          count:
            description: Number of items you would like to receive.
            type: integer
            example: 1
            required: false
        responses:
          503:
            description: |
              Server Unavailable. Check Your Rate Limits.
      post?:
        responses:
          503:
            description: |
              Server Unavailable. Check Your Rate Limits.
      delete?:
        responses:
          503:
            description: |
              Server Unavailable. Check Your Rate Limits.
documentation:
  - title: test chapter
    content: Nothing here.
  - title: Authentication
    content: |
      ![test image](tool_time.jpg)

      Ipsum lorem and a [link to Google](https://google.com)

      ### Heading 3

      Ipsum lorem

      List following:

      - Level 1
        * Level 2
        * Level 2
      - Level 1:
        * *Server-side* flow (reccommended): Level 2
        * *Implicit flow*: Level 2

      #### Level 4

      ```
      code block
      ```

      *Note:* Notes and [a link](#).

      *Note:* Second note

      ```
      Code block
      ```

      Paragraph before a table:

      | Head 1 | Head 2 | Head 3 |
      | --- | --- | --- |
      | 1 | 1 | 1 |
      | 2 | 2 | 2 |
      | 3 | 3 | 3 |

      Paragraph after a table

      #### Heading 4

      Another list incoming:

      * List item 1

          *Note:* In a list.

      * List item 2

      For example, you could request an access_token like so:

      ```
      long code block
      curl \-F 'client_id=CLIENT-ID' \
          -F 'client_secret=CLIENT-SECRET' \
          -F 'grant_type=authorization_code' \
          -F 'redirect_uri=YOUR-REDIRECT-URI' \
          -F 'code=CODE' \link
      ```

      Example reply:

      ```json
      {
          "access_token": "12j2u3ouvyto8ygosuhbjf",
          "user": {
              "id": "12345",
              "username": "hi",
              "full_name": "Hi There",
              "profile_picture": "a_pic.jpg"
          }
      }
      ```
# Users
/users:
  /{userId}:
    uriParameters:
      userId:
        type: integer
    type: base
    get:
      description: Get basic information about a user.
      responses:
        200:
          body:
            schema: |
              {
                  "": "http://json-schema.org/draft-03/schema",
                  "type": "object",
                  "properties": {
                      "data": {
                          "properties": {
                              "id": {
                                  "type": "string"
                              },
                              "username": {
                                  "type": "string"
                              },
                              "full_name": {
                                  "type": "string"
                              },
                              "profile_picture": {
                                  "type": "string"
                              },
                              "bio": {
                                  "type": "string"
                              },
                              "website": {
                                  "type": "string"
                              },
                              "counts": {
                                  "properties": {
                                      "media": {
                                          "type": "integer"
                                      },
                                      "follows": {
                                          "type": "integer"
                                      },
                                      "followed_by": {
                                          "type": "integer"
                                      }
                                  },
                                  "type": "object"
                              }
                          },
                          "type": "object"
                      }
                  }
              }
            example: |
              {
                  "data": {
                      "id": "1574083",
                      "username": "snoopdogg",
                      "full_name": "Snoop Dogg",
                      "profile_picture": "http://distillery.s3.amazonaws.com/profiles/profile_1574083_75sq_1295469061.jpg",
                      "bio": "This is my bio",
                      "website": "http://snoopdogg.com",
                      "counts": {
                          "media": 1320,
                          "follows": 420,
                          "followed_by": 3410
                      }
                  }
              }
    # Follows
    /follows:
      securedBy: [ oauth_2_0: { scopes: [ relationships ] } ]
      type: base
      get:
        description: Get the list of users this user follows.
        responses:
          200:
            body:
              schema: |
                {
                    "": "http://json-schema.org/draft-03/schema",
                    "type": "object",
                    "properties": {
                        "data": [
                            {
                                "properties": {
                                    "username": {
                                        "type": "string"
                                    },
                                    "first_name": {
                                        "type": "string"
                                    },
                                    "profile_picture": {
                                        "type": "string"
                                    },
                                    "id": {
                                        "type": "string"
                                    },
                                    "last_name": {
                                        "type": "string"
                                    }
                                },
                                "type": "object"
                            }
                        ],
                        "type": "array"
                    }
                }
              example: |
                {
                    "data": [{
                        "username": "jack",
                        "first_name": "Jack",
                        "profile_picture": "http://distillery.s3.amazonaws.com/profiles/profile_66_75sq.jpg",
                        "id": "66",
                        "last_name": "Dorsey"
                    },
                    {
                        "username": "sammyjack",
                        "first_name": "Sammy",
                        "profile_picture": "http://distillery.s3.amazonaws.com/profiles/profile_29648_75sq_1294520029.jpg",
                        "id": "29648",
                        "last_name": "Jack"
                    },
                    {
                        "username": "jacktiddy",
                        "first_name": "Jack",
                        "profile_picture": "http://distillery.s3.amazonaws.com/profiles/profile_13096_75sq_1286441317.jpg",
                        "id": "13096",
                        "last_name": "Tiddy"
                    }]
                }
    # Followed by
    /followed-by:
      securedBy: [ oauth_2_0: { scopes: [ relationships ] } ]
      type: base
      get:
        description: Get the list of users this user is followed by.
        responses:
          200:
            body:
              schema: |
                {
                    "": "http://json-schema.org/draft-03/schema",
                    "type": "object",
                    "properties": {
                        "data": [
                            {
                                "properties": {
                                    "username": {
                                        "type": "string"
                                    },
                                    "first_name": {
                                        "type": "string"
                                    },
                                    "profile_picture": {
                                        "type": "string"
                                    },
                                    "id": {
                                        "type": "string"
                                    },
                                    "last_name": {
                                        "type": "string"
                                    }
                                },
                                "type": "object"
                            }
                        ],
                        "type": "array"
                    }
                }
              example: |
                {
                    "data": [{
                        "username": "jack",
                        "first_name": "Jack",
                        "profile_picture": "http://distillery.s3.amazonaws.com/profiles/profile_66_75sq.jpg",
                        "id": "66",
                        "last_name": "Dorsey"
                    },
                    {
                        "username": "sammyjack",
                        "first_name": "Sammy",
                        "profile_picture": "http://distillery.s3.amazonaws.com/profiles/profile_29648_75sq_1294520029.jpg",
                        "id": "29648",
                        "last_name": "Jack"
                    },
                    {
                        "username": "jacktiddy",
                        "first_name": "Jack",
                        "profile_picture": "http://distillery.s3.amazonaws.com/profiles/profile_13096_75sq_1286441317.jpg",
                        "id": "13096",
                        "last_name": "Tiddy"
                    }]
                }
    # Requested by
    /self/requested-by:
      securedBy: [ oauth_2_0: { scopes: [ relationships ] } ]
      get:
        description: |
          List the users who have requested this user's permission to follow.
        responses:
          200:
            body:
              schema: |
                {
                    "": "http://json-schema.org/draft-03/schema",
                    "type": "object",
                    "properties": {
                        "meta": {
                            "properties": {
                                "code": {
                                    "type": "integer"
                                }
                            },
                            "type": "object"
                        },
                        "data": [
                            {
                                "properties": {
                                    "username": {
                                        "type": "string"
                                    },
                                    "profile_picture": {
                                        "type": "string"
                                    },
                                    "id": {
                                        "type": "string"
                                    }
                                },
                                "type": "object"
                            }
                        ]
                    }
                }
              example: |
                {
                    "meta": {
                        "code": 200
                    },
                    "data": [
                        {
                            "username": "mikeyk",
                            "profile_picture": "http://distillery.s3.amazonaws.com/profiles/profile_4_75sq_1292324747_debug.jpg",
                            "id": "4"
                        }
                    ]
                }
    /media/recent:
      type: base
      get:
        is: [ limitableById, limitableByTime ]
        description: |
          See the authenticated user's feed. May return a mix of both image and
          video types.
        responses:
          200:
            body:
              example: |
                {
                    "data": [{
                        "location": {
                            "id": "833",
                            "latitude": 37.77956816727314,
                            "longitude": -122.41387367248539,
                            "name": "Civic Center BART"
                        },
                        "comments": {
                            "count": 16,
                            "data": [ ... ]
                        },
                        "caption": null,
                        "link": "http://instagr.am/p/BXsFz/",
                        "likes": {
                            "count": 190,
                            "data": [{
                                "username": "shayne",
                                "full_name": "Shayne Sweeney",
                                "id": "20",
                                "profile_picture": "..."
                            }, {...subset of likers...}]
                        },
                        "created_time": "1296748524",
                        "images": {
                            "low_resolution": {
                                "url": "http://distillery.s3.amazonaws.com/media/2011/02/03/efc502667a554329b52d9a6bab35b24a_6.jpg",
                                "width": 306,
                                "height": 306
                            },
                            "thumbnail": {
                                "url": "http://distillery.s3.amazonaws.com/media/2011/02/03/efc502667a554329b52d9a6bab35b24a_5.jpg",
                                "width": 150,
                                "height": 150
                            },
                            "standard_resolution": {
                                "url": "http://distillery.s3.amazonaws.com/media/2011/02/03/efc502667a554329b52d9a6bab35b24a_7.jpg",
                                "width": 612,
                                "height": 612
                            }
                        },
                        "type": "image",
                        "users_in_photo": [],
                        "filter": "Earlybird",
                        "tags": [],
                        "id": "22987123",
                        "user": {
                            "username": "kevin",
                            "full_name": "Kevin S",
                            "profile_picture": "http://distillery.s3.amazonaws.com/profiles/profile_3_75sq_1295574122.jpg",
                            "id": "3"
                        }
                    },
                    {
                        "videos": {
                            "low_resolution": {
                                "url": "http://distilleryvesper9-13.ak.instagram.com/090d06dad9cd11e2aa0912313817975d_102.mp4",
                                "width": 480,
                                "height": 480
                            },
                            "standard_resolution": {
                                "url": "http://distilleryvesper9-13.ak.instagram.com/090d06dad9cd11e2aa0912313817975d_101.mp4",
                                "width": 640,
                                "height": 640
                            },
                        "comments": {
                            "data": [{
                                "created_time": "1279332030",
                                "text": "Love the sign here",
                                "from": {
                                    "username": "mikeyk",
                                    "full_name": "Mikey Krieger",
                                    "id": "4",
                                    "profile_picture": "http://distillery.s3.amazonaws.com/profiles/profile_1242695_75sq_1293915800.jpg"
                                },
                                "id": "8"
                            },
                            {
                                "created_time": "1279341004",
                                "text": "Chilako taco",
                                "from": {
                                    "username": "kevin",
                                    "full_name": "Kevin S",
                                    "id": "3",
                                    "profile_picture": "..."
                                },
                                "id": "3"
                            }],
                            "count": 2
                        },
                        "caption": null,
                        "likes": {
                            "count": 1,
                            "data": [{
                                "username": "mikeyk",
                                "full_name": "Mikeyk",
                                "id": "4",
                                "profile_picture": "..."
                            }]
                        },
                        "link": "http://instagr.am/p/D/",
                        "created_time": "1279340983",
                        "images": {
                            "low_resolution": {
                                "url": "http://distilleryimage2.ak.instagram.com/11f75f1cd9cc11e2a0fd22000aa8039a_6.jpg",
                                "width": 306,
                                "height": 306
                            },
                            "thumbnail": {
                                "url": "http://distilleryimage2.ak.instagram.com/11f75f1cd9cc11e2a0fd22000aa8039a_5.jpg",
                                "width": 150,
                                "height": 150
                            },
                            "standard_resolution": {
                                "url": "http://distilleryimage2.ak.instagram.com/11f75f1cd9cc11e2a0fd22000aa8039a_7.jpg",
                                "width": 612,
                                "height": 612
                            }
                        },
                        "type": "video",
                        "users_in_photo": null,
                        "filter": "Vesper",
                        "tags": [],
                        "id": "363839373298",
                        "user": {
                            "username": "kevin",
                            "full_name": "Kevin S",
                            "profile_picture": "http://distillery.s3.amazonaws.com/profiles/profile_3_75sq_1295574122.jpg",
                            "id": "3"
                        },
                        "location": null
                    },
                    ...]
                }
    /relationship:
      securedBy: [ oauth_2_0: { scopes: [ relationships ] } ]
      type: base
      get:
        description: Get information about a relationship to another user.
        responses:
          200:
            body:
              schema: |
                {
                    "": "http://json-schema.org/draft-03/schema",
                    "type": "object",
                    "properties": {
                        "meta": {
                            "properties": {
                                "code": {
                                    "type": "integer"
                                }
                            },
                            "type": "object"
                        },
                        "data": {
                            "properties": {
                                "outgoing_status": {
                                    "enum": [
                                        "follows",
                                        "requested",
                                        "none"
                                    ]
                                },
                                "incoming_status": {
                                    "enum": [
                                        "followed_by",
                                        "requested_by",
                                        "blocked_by_you",
                                        "none"
                                    ]
                                }
                            },
                            "type": "object"
                        }
                    }
                }
              example: |
                {
                    "meta": {
                        "code": 200
                    },
                    "data": {
                        "outgoing_status": "none",
                        "incoming_status": "requested_by"
                    }
                }
      post:
        description: |
          Modify the relationship between the current user and the target user.
        body:
          properties:
            action:
              description: One of follow/unfollow/block/unblock/approve/deny.
              enum:
                - follow
                - unfollow
                - block
                - unblock
                - approve
                - deny
        responses:
          200:
            body:
              schema: |
                {
                    "": "http://json-schema.org/draft-03/schema",
                    "type": "object",
                    "properties": {
                        "meta": {
                            "properties": {
                                "code": {
                                    "type": "integer"
                                }
                            },
                            "type": "object"
                        },
                        "data": {
                            "properties": {
                                "outgoing_status": {
                                    "enum": [
                                        "follows",
                                        "requested",
                                        "none"
                                    ]
                                },
                                "incoming_status": {
                                    "enum": [
                                        "followed_by",
                                        "requested_by",
                                        "blocked_by_you",
                                        "none"
                                    ]
                                }
                            },
                            "type": "object"
                        }
                    }
                }
              example: |
                {
                    "meta": {
                        "code": 200
                    },
                    "data": {
                        "outgoing_status": "none",
                        "incoming_status": "requested_by"
                    }
                }
  /search:
    type: base
    get:
      description: Search for a user by name.
      queryParameters:
        q:
          description: A query string.
          type: string
          required: true
        count:
          description: Number of users to return.
          type: integer
      responses:
        200:
          body:
            schema: |
              {
                  "": "http://json-schema.org/draft-03/schema",
                  "type": "object",
                  "properties": {
                      "data": [
                          {
                              "properties": {
                                  "username": {
                                      "type": "string"
                                  },
                                  "first_name": {
                                      "type": "string"
                                  },
                                  "profile_picture": {
                                      "type": "string"
                                  },
                                  "id": {
                                      "type": "string"
                                  },
                                  "last_name": {
                                      "type": "string"
                                  }
                              },
                              "type": "object"
                          }
                      ],
                      "type": "array"
                  }
              }
            example: |
              {
                  "data": [{
                      "username": "jack",
                      "first_name": "Jack",
                      "profile_picture": "http://distillery.s3.amazonaws.com/profiles/profile_66_75sq.jpg",
                      "id": "66",
                      "last_name": "Dorsey"
                  },
                  {
                      "username": "sammyjack",
                      "first_name": "Sammy",
                      "profile_picture": "http://distillery.s3.amazonaws.com/profiles/profile_29648_75sq_1294520029.jpg",
                      "id": "29648",
                      "last_name": "Jack"
                  },
                  {
                      "username": "jacktiddy",
                      "first_name": "Jack",
                      "profile_picture": "http://distillery.s3.amazonaws.com/profiles/profile_13096_75sq_1286441317.jpg",
                      "id": "13096",
                      "last_name": "Tiddy"
                  }]
              }
  /self:
    /feed:
      type: base
      get:
        is: [ limitableById ]
        description: |
          See the authenticated user's feed. May return a mix of both image and
          video types.
        responses:
          200:
            body:
              example: |
                {
                    "data": [{
                        "location": {
                            "id": "833",
                            "latitude": 37.77956816727314,
                            "longitude": -122.41387367248539,
                            "name": "Civic Center BART"
                        },
                        "comments": {
                            "count": 16,
                            "data": [ ... ]
                        },
                        "caption": null,
                        "link": "http://instagr.am/p/BXsFz/",
                        "likes": {
                            "count": 190,
                            "data": [{
                                "username": "shayne",
                                "full_name": "Shayne Sweeney",
                                "id": "20",
                                "profile_picture": "..."
                            }, {...subset of likers...}]
                        },
                        "created_time": "1296748524",
                        "images": {
                            "low_resolution": {
                                "url": "http://distillery.s3.amazonaws.com/media/2011/02/03/efc502667a554329b52d9a6bab35b24a_6.jpg",
                                "width": 306,
                                "height": 306
                            },
                            "thumbnail": {
                                "url": "http://distillery.s3.amazonaws.com/media/2011/02/03/efc502667a554329b52d9a6bab35b24a_5.jpg",
                                "width": 150,
                                "height": 150
                            },
                            "standard_resolution": {
                                "url": "http://distillery.s3.amazonaws.com/media/2011/02/03/efc502667a554329b52d9a6bab35b24a_7.jpg",
                                "width": 612,
                                "height": 612
                            }
                        },
                        "type": "image",
                        "users_in_photo": [],
                        "filter": "Earlybird",
                        "tags": [],
                        "id": "22987123",
                        "user": {
                            "username": "kevin",
                            "full_name": "Kevin S",
                            "profile_picture": "http://distillery.s3.amazonaws.com/profiles/profile_3_75sq_1295574122.jpg",
                            "id": "3"
                        }
                    },
                    {
                        "videos": {
                            "low_resolution": {
                                "url": "http://distilleryvesper9-13.ak.instagram.com/090d06dad9cd11e2aa0912313817975d_102.mp4",
                                "width": 480,
                                "height": 480
                            },
                            "standard_resolution": {
                                "url": "http://distilleryvesper9-13.ak.instagram.com/090d06dad9cd11e2aa0912313817975d_101.mp4",
                                "width": 640,
                                "height": 640
                            },
                        "comments": {
                            "data": [{
                                "created_time": "1279332030",
                                "text": "Love the sign here",
                                "from": {
                                    "username": "mikeyk",
                                    "full_name": "Mikey Krieger",
                                    "id": "4",
                                    "profile_picture": "http://distillery.s3.amazonaws.com/profiles/profile_1242695_75sq_1293915800.jpg"
                                },
                                "id": "8"
                            },
                            {
                                "created_time": "1279341004",
                                "text": "Chilako taco",
                                "from": {
                                    "username": "kevin",
                                    "full_name": "Kevin S",
                                    "id": "3",
                                    "profile_picture": "..."
                                },
                                "id": "3"
                            }],
                            "count": 2
                        },
                        "caption": null,
                        "likes": {
                            "count": 1,
                            "data": [{
                                "username": "mikeyk",
                                "full_name": "Mikeyk",
                                "id": "4",
                                "profile_picture": "..."
                            }]
                        },
                        "link": "http://instagr.am/p/D/",
                        "created_time": "1279340983",
                        "images": {
                            "low_resolution": {
                                "url": "http://distilleryimage2.ak.instagram.com/11f75f1cd9cc11e2a0fd22000aa8039a_6.jpg",
                                "width": 306,
                                "height": 306
                            },
                            "thumbnail": {
                                "url": "http://distilleryimage2.ak.instagram.com/11f75f1cd9cc11e2a0fd22000aa8039a_5.jpg",
                                "width": 150,
                                "height": 150
                            },
                            "standard_resolution": {
                                "url": "http://distilleryimage2.ak.instagram.com/11f75f1cd9cc11e2a0fd22000aa8039a_7.jpg",
                                "width": 612,
                                "height": 612
                            }
                        },
                        "type": "video",
                        "users_in_photo": null,
                        "filter": "Vesper",
                        "tags": [],
                        "id": "363839373298",
                        "user": {
                            "username": "kevin",
                            "full_name": "Kevin S",
                            "profile_picture": "http://distillery.s3.amazonaws.com/profiles/profile_3_75sq_1295574122.jpg",
                            "id": "3"
                        },
                        "location": null
                    },
                    ...]
                }
    /media/liked:
      type: base
      get:
        description: |
          See the authenticated user's list of media they've liked. May return
          a mix of both image and video types.

          *Note:* This list is ordered by the order in which the user liked the
          media. Private media is returned as long as the authenticated user
          has permission to view that media. Liked media lists are only
          available for the currently authenticated user.
        queryParameters:
          max_like_id:
            description: Return media liked before this id.
            type: integer
        responses:
          200:
            body:
              example: |
                {
                    "data": [{
                        "location": {
                            "id": "833",
                            "latitude": 37.77956816727314,
                            "longitude": -122.41387367248539,
                            "name": "Civic Center BART"
                        },
                        "comments": {
                            "count": 16,
                            "data": [ ... ]
                        },
                        "caption": null,
                        "link": "http://instagr.am/p/BXsFz/",
                        "likes": {
                            "count": 190,
                            "data": [{
                                "username": "shayne",
                                "full_name": "Shayne Sweeney",
                                "id": "20",
                                "profile_picture": "..."
                            }, {...subset of likers...}]
                        },
                        "created_time": "1296748524",
                        "images": {
                            "low_resolution": {
                                "url": "http://distillery.s3.amazonaws.com/media/2011/02/03/efc502667a554329b52d9a6bab35b24a_6.jpg",
                                "width": 306,
                                "height": 306
                            },
                            "thumbnail": {
                                "url": "http://distillery.s3.amazonaws.com/media/2011/02/03/efc502667a554329b52d9a6bab35b24a_5.jpg",
                                "width": 150,
                                "height": 150
                            },
                            "standard_resolution": {
                                "url": "http://distillery.s3.amazonaws.com/media/2011/02/03/efc502667a554329b52d9a6bab35b24a_7.jpg",
                                "width": 612,
                                "height": 612
                            }
                        },
                        "type": "image",
                        "users_in_photo": [],
                        "filter": "Earlybird",
                        "tags": [],
                        "id": "22987123",
                        "user": {
                            "username": "kevin",
                            "full_name": "Kevin S",
                            "profile_picture": "http://distillery.s3.amazonaws.com/profiles/profile_3_75sq_1295574122.jpg",
                            "id": "3"
                        }
                    },
                    {
                        "videos": {
                            "low_resolution": {
                                "url": "http://distilleryvesper9-13.ak.instagram.com/090d06dad9cd11e2aa0912313817975d_102.mp4",
                                "width": 480,
                                "height": 480
                            },
                            "standard_resolution": {
                                "url": "http://distilleryvesper9-13.ak.instagram.com/090d06dad9cd11e2aa0912313817975d_101.mp4",
                                "width": 640,
                                "height": 640
                            },
                        "comments": {
                            "data": [{
                                "created_time": "1279332030",
                                "text": "Love the sign here",
                                "from": {
                                    "username": "mikeyk",
                                    "full_name": "Mikey Krieger",
                                    "id": "4",
                                    "profile_picture": "http://distillery.s3.amazonaws.com/profiles/profile_1242695_75sq_1293915800.jpg"
                                },
                                "id": "8"
                            },
                            {
                                "created_time": "1279341004",
                                "text": "Chilako taco",
                                "from": {
                                    "username": "kevin",
                                    "full_name": "Kevin S",
                                    "id": "3",
                                    "profile_picture": "..."
                                },
                                "id": "3"
                            }],
                            "count": 2
                        },
                        "caption": null,
                        "likes": {
                            "count": 1,
                            "data": [{
                                "username": "mikeyk",
                                "full_name": "Mikeyk",
                                "id": "4",
                                "profile_picture": "..."
                            }]
                        },
                        "link": "http://instagr.am/p/D/",
                        "created_time": "1279340983",
                        "images": {
                            "low_resolution": {
                                "url": "http://distilleryimage2.ak.instagram.com/11f75f1cd9cc11e2a0fd22000aa8039a_6.jpg",
                                "width": 306,
                                "height": 306
                            },
                            "thumbnail": {
                                "url": "http://distilleryimage2.ak.instagram.com/11f75f1cd9cc11e2a0fd22000aa8039a_5.jpg",
                                "width": 150,
                                "height": 150
                            },
                            "standard_resolution": {
                                "url": "http://distilleryimage2.ak.instagram.com/11f75f1cd9cc11e2a0fd22000aa8039a_7.jpg",
                                "width": 612,
                                "height": 612
                            }
                        },
                        "type": "video",
                        "users_in_photo": null,
                        "filter": "Vesper",
                        "tags": [],
                        "id": "363839373298",
                        "user": {
                            "username": "kevin",
                            "full_name": "Kevin S",
                            "profile_picture": "http://distillery.s3.amazonaws.com/profiles/profile_3_75sq_1295574122.jpg",
                            "id": "3"
                        },
                        "location": null
                    },
                    ...]
                }
# Oembed
/p/{shortcode}/media:
  uriParameters:
    shortcode:
      type: string
      required: true
  type: base
  get:
    description: |
      Given a short link, issues a redirect to that media's JPG file.
    queryParameters:
      size:
        enum:
          - t,
          - m,
          - l
        default: m
    responses:
      302:
        body:
          text/html:
            example: |
              HTTP/1.1 302 FOUND
              Location: http://distillery.s3.amazonaws.com/media/2010/10/02/7e4051fdcf1d45ab9bc1fba2582c0c6b_6.jpg
